spring:
  application.name: Project
  devtools:
    restart:
      enabled: true
  datasource:
    url: jdbc:postgresql://localhost:5432/project
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
  jpa:
    properties.hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate.ddl-auto: update
    show-sql: true
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.example.project.entity
#  configuration:
#    map-underscore-to-camel-case: true
#  config-location: classpath:mybatis-config.xml
jwt:
  secret: ${JWT_SECRET}
  expiration: 86400000
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html

file:
  upload-dir: ./images
 