name: CI/CD

on:
  push:
    branches: main

jobs:
  Traivel:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Set execute permission for gradlew
        run: chmod +x ./gradle

      - name: Build the Gradle
        run: ./gradlew clean build --exclude-task test

      - name: Copy jar to EC2 server
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.HOST }}
          user: ${{ secrets.USER }}
          key: ${{ secrets.KEY }}
          source: "/build/libs/"
          target: "/home/ubuntu/traivel/Project-0.0.1-SNAPSHOT.jar"
          script: chmod 755 /home/ubuntu/traivel/build/libs/Project-0.0.1-SNAPSHOT.jar

      - name: Restart server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          user: ${{ secrets.USER }}
          key: ${{ secrets.KEY }}
          script: |
            sudo systemctl daemon-reload
            sudo systemctl restart traivel